name: flutter_app
description: A new Flutter project.
# 其他配置项...

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  video_player: ^2.8.2
  device_info_plus: ^10.1.0
  flutter_contacts: ^1.1.7
  photo_manager: ^3.0.0
  sms_advanced: ^1.1.0
  http: ^0.13.5 

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png
  
flutter:
  assets:
    - assets/A.mp4
    - assets/B.png